name: Build Hash Router

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - docusaurus-v**
    paths:
      - packages/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Hash Router
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18'
          cache: yarn
      - name: Installation
        run: yarn
      - name: Build Hash Router
        run: yarn build:website:fast
        env:
          DOCUSAURUS_ROUTER: 'hash'
          BASE_URL: '/docusaurus/' # GH pages deploys under https://facebook.github.io/docusaurus/
      - name: Upload Website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-hash-router-archive
          path: website/build
      - name: Upload Website Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/build

  # See https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
  deploy:
    name: Deploy to GitHub Pages
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main')}}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
