name: Swizzle Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/**

permissions:
  contents: read

jobs:
  test:
    name: Swizzle
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: ['eject', 'wrap']
        variant: ['js', 'ts']
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3
      - name: Set up Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3
        with:
          node-version: '16'
          cache: yarn
      - name: Installation
        run: yarn

      # Swizzle all the theme components
      - name: Swizzle (${{matrix.action}} - ${{matrix.variant}})
        run: yarn workspace website test:swizzle:${{matrix.action}}:${{matrix.variant}}
      # Build swizzled site
      - name: Build website
        run: yarn build:website:fast
      # Ensure swizzled site still typechecks
      - name: TypeCheck website
        run: yarn workspace website typecheck
